export const ActionTypes = {
  SEARCH_MOVIE: "SEARCH_MOVIE",
  ADD_TO_LIST: "ADD_TO_LIST",
  REMOVE_FROM_LIST: "REMOVE_FROM_LIST",
  ADD_POST_MOVIES:"ADD_POST_MOVIES",
  SET_LINK_ACTIVE: "SET_LINKACTIVE",
  SLIDER: "SLIDER",
};
