export const ActionTypes = {
  SEARCH_MOVIE: "SEARCH_MOVIE",
  ADD_TO_LIST: "ADD_TO_LIST",
  REMOVE_FROM_LIST: "REMOVE_FROM_LIST",
  POST_MOVIES: "POST_MOVIES",
  SLIDER: "SLIDER",
  SET_LINK_ACTIVE: "SET_LINK_ACTIVE",
};
